### PR TITLE
Added language option bar in navbar

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
I've added all the files. Please look into it. Thank you.
Issue: #50 

Netflix clone

### CODE REVIEW

**Comment by ahmadsohail404** [comment]
make the language button smaller to resemble sign in button

**Comment by ahmadsohail404** [comment]
@Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
I adjust the width of the button. It looks similar as sign In button.

**Comment by ahmadsohail404** [comment]
resolve conflicts

**Pull request closed without merging**
