### PR TITLE
Updated sign up form with social media login

### PR DESCRIPTION
**Pull request by LunlunChin**
Hi, this is my first time trying an open source project!

I've recently added the social media login button in the sign up form.

Thank you!
Capture

### CODE REVIEW

**Comment by ahmadsohail404** [comment]
in social media, change the color of icons to their respective colors and resolve conflicts

**Comment by ahmadsohail404** [comment]
Also host it

**Comment by LunlunChin** [comment]
Capture
This is the latest update of the social media button, according to their color code

**Comment by LunlunChin** [comment]
https://lunlunchin.github.io/Netflix-UI-LandingPage/signup.html

**Comment by ahmadsohail404** [comment]
resolve conflicts

**Comment by ahmadsohail404** [comment]
I have resolved the conflicts and merged it :)

**Pull request merged**
