### PR TITLE
Scroll to top functionality.

### PR DESCRIPTION
**Pull request by aditya-singh9**
Added a button in which it scrolls to the top with smooth scrolling. It appears when user starts scrolling the page and disappears when user is on the top of the page.

### CODE REVIEW

**Comment by ahmadsohail404** [comment]
host it and put the link here in comment

**Comment by aditya-singh9** [comment]
Here you go -   https://aditya-singh9.github.io/Netflix-UI-LandingPage/

**Comment by aditya-singh9** [comment]
> host it and put the link here in comment

https://aditya-singh9.github.io/Netflix-UI-LandingPage/

#hacktoberfest

**Comment by ahmadsohail404** [comment]
resolve conflicts

**Comment by aditya-singh9** [comment]
> resolve conflicts

RESOLVED! 👍

**Pull request merged**
