### PR TITLE
added localization with a support of हिन्दी language; closes #30

### LINKED ISSUE #30: Add support for regional language (Hindi)
Similar to the <a href="https://www.netflix.com/in/">official website</a> we can add support for Hindi language as well.

### PR DESCRIPTION
**Pull request by iamHrithikRaj**
Now the website supports हिन्दी as language.
closes #30

Screen Shot 2021-10-05 at 5 05 33 AM

### CODE REVIEW

**Comment by ahmadsohail404** [comment]
host it and share the link here

**Comment by iamHrithikRaj** [comment]
@ahmadsohail404 resolved conflicts. ready to merge

**Comment by iamHrithikRaj** [comment]
> host it and share the link here

the clone website supports both the languages, no need to host it separately. But if you insist I can do that. Let me know

**Comment by ahmadsohail404** [comment]
we shall keep it hosted in a single website only, resolve conflicts

**Comment by iamHrithikRaj** [comment]
@ahmadsohail404 resolved conflicts

**Comment by ahmadsohail404** [comment]
@iamHrithikRaj mannn, it has a lot of bugs

**Comment by ahmadsohail404** [comment]
unwanted sign in button of left side, front banner text aint converting to hindi,, faqs are ruined

**Comment by iamHrithikRaj** [comment]
@ahmadsohail404 I think there was issue will git conflict rest the code is correct i'm resolving the issue gimme a 2mins

**Pull request merged**
